param(
    [string]$OutputDir = ""
)

$ErrorActionPreference = "Stop"

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Write-WarnMsg {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Read-Required {
    param([string]$Prompt)

    while ($true) {
        $value = Read-Host $Prompt
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            return $value.Trim()
        }

        Write-WarnMsg "This value is required."
    }
}

function Read-Optional {
    param(
        [string]$Prompt,
        [string]$DefaultValue = ""
    )

    $value = Read-Host $Prompt
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $DefaultValue
    }

    return $value.Trim()
}

function ConvertTo-JsString {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return '""'
    }

    return ($Value | ConvertTo-Json -Compress)
}

function Add-Step {
    param(
        [System.Collections.Generic.List[string]]$Steps,
        [string]$Code,
        [string]$Label
    )

    $Steps.Add("  $Code")
    Write-Ok "Added: $Label"
}

function Read-Timeout {
    param([string]$Prompt)

    $value = Read-Optional -Prompt $Prompt -DefaultValue "10000"
    $timeout = 0
    if (-not [int]::TryParse($value, [ref]$timeout) -or $timeout -lt 0) {
        Write-WarnMsg "Invalid timeout. Using 10000."
        return 10000
    }

    return $timeout
}

function Get-OutputScriptPath {
    param(
        [string]$InputPath,
        [string]$DefaultDir,
        [string]$DefaultName
    )

    $path = $InputPath
    if ([string]::IsNullOrWhiteSpace($path)) {
        $path = Join-Path $DefaultDir $DefaultName
    }
    else {
        $path = [Environment]::ExpandEnvironmentVariables($path.Trim().Trim('"'))
    }

    $pathEndsWithSeparator = $path.EndsWith("\") -or $path.EndsWith("/")
    if ($pathEndsWithSeparator) {
        $path = Join-Path $path $DefaultName
    }

    if ([string]::IsNullOrWhiteSpace([System.IO.Path]::GetExtension($path))) {
        $path = "$path.js"
    }

    if ([System.IO.Path]::IsPathRooted($path)) {
        return [System.IO.Path]::GetFullPath($path)
    }

    $directoryPart = Split-Path -Parent $path
    if ([string]::IsNullOrWhiteSpace($directoryPart)) {
        return [System.IO.Path]::GetFullPath((Join-Path $DefaultDir $path))
    }

    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location).Path $path))
}

function Write-StartBat {
    param([string]$ScriptPath)

    $projectDir = Split-Path -Parent $ScriptPath
    $scriptName = Split-Path -Leaf $ScriptPath
    $startPath = Join-Path $projectDir "start.bat"

    $lines = @(
        "@echo off",
        "chcp 65001 >nul",
        "setlocal EnableExtensions",
        "",
        "REM Generated by browser_auto.ps1.",
        "REM Checks the local Node.js environment, installs Playwright into this project directory, and runs the generated script.",
        "",
        "cd /d ""%~dp0""",
        "",
        "where node >nul 2>nul",
        "if errorlevel 1 (",
        "    echo [ERROR] Node.js was not found. Please install Node.js 18 or later.",
        "    pause",
        "    exit /b 1",
        ")",
        "",
        "where npm >nul 2>nul",
        "if errorlevel 1 (",
        "    echo [ERROR] npm was not found. Please install Node.js with npm.",
        "    pause",
        "    exit /b 1",
        ")",
        "",
        "if not exist ""package.json"" (",
        "    echo [INFO] Creating package.json in %CD%",
        "    call npm init -y",
        "    if errorlevel 1 exit /b 1",
        ")",
        "",
        "if not exist ""node_modules\playwright\package.json"" (",
        "    echo [INFO] Installing Playwright into %CD%",
        "    call npm install playwright",
        "    if errorlevel 1 exit /b 1",
        ")",
        "",
        "echo [INFO] Ensuring Chromium browser is installed",
        "call npx playwright install chromium",
        "if errorlevel 1 exit /b 1",
        "",
        "echo [INFO] Running $scriptName",
        "node ""%~dp0$scriptName""",
        "set ""EXIT_CODE=%ERRORLEVEL%""",
        "",
        "echo.",
        "pause",
        "exit /b %EXIT_CODE%"
    )

    Set-Content -LiteralPath $startPath -Value $lines -Encoding UTF8
    return $startPath
}

function Show-Menu {
    Write-Host ""
    Write-Host "========================================"
    Write-Host "Browser Automation Script Generator"
    Write-Host "========================================"
    Write-Host "1. Open URL"
    Write-Host "2. Click by XPath"
    Write-Host "3. Fill by XPath"
    Write-Host "4. Click then fill by XPath"
    Write-Host "5. Wait for XPath"
    Write-Host "6. Wait milliseconds"
    Write-Host "7. Press key by XPath"
    Write-Host "8. Select option by XPath"
    Write-Host "9. Check checkbox by XPath"
    Write-Host "10. Uncheck checkbox by XPath"
    Write-Host "11. Hover by XPath"
    Write-Host "12. Screenshot"
    Write-Host "13. Add custom JavaScript"
    Write-Host "14. Show steps"
    Write-Host "15. Clear steps"
    Write-Host "16. Save script and exit"
    Write-Host "0. Exit without saving"
    Write-Host ""
}

function Show-Steps {
    param([System.Collections.Generic.List[string]]$Steps)

    Write-Host ""
    if ($Steps.Count -eq 0) {
        Write-WarnMsg "No steps added yet."
        return
    }

    Write-Host "Current steps:"
    for ($index = 0; $index -lt $Steps.Count; $index++) {
        Write-Host ("{0}. {1}" -f ($index + 1), $Steps[$index].Trim())
    }
}

function Save-AutomationScript {
    param(
        [System.Collections.Generic.List[string]]$Steps,
        [string]$TargetDir
    )

    if ($Steps.Count -eq 0) {
        Write-WarnMsg "Add at least one step before saving."
        return $false
    }

    if ([string]::IsNullOrWhiteSpace($TargetDir)) {
        $dailyRoot = Split-Path -Parent $PSScriptRoot
        $TargetDir = Join-Path $dailyRoot "output\browser_automation"
    }

    if (-not (Test-Path -LiteralPath $TargetDir)) {
        New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
    }

    $defaultName = "browser_auto_run_{0}.js" -f (Get-Date -Format "yyyyMMdd_HHmmss")
    $defaultPath = Join-Path $TargetDir $defaultName
    $outputPath = Read-Optional -Prompt "Output script path (default $defaultPath)" -DefaultValue $defaultPath
    $targetPath = Get-OutputScriptPath -InputPath $outputPath -DefaultDir $TargetDir -DefaultName $defaultName
    $targetDir = Split-Path -Parent $targetPath

    if (-not (Test-Path -LiteralPath $targetDir)) {
        New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    }

    $keepOpenAnswer = Read-Optional -Prompt "Keep browser open at the end? (Y/N, default Y)" -DefaultValue "Y"
    $keepOpen = $keepOpenAnswer -notmatch '^(N|n|No|no)$'

    $scriptLines = New-Object System.Collections.Generic.List[string]
    $scriptLines.Add("// Generated by browser_auto.ps1")
    $scriptLines.Add("// Install dependency once: npm install playwright")
    $scriptLines.Add("const { chromium } = require('playwright');")
    $scriptLines.Add("")
    $scriptLines.Add("(async () => {")
    $scriptLines.Add("  const browser = await chromium.launch({ headless: false });")
    $scriptLines.Add("  const page = await browser.newPage();")
    $scriptLines.Add("")
    $scriptLines.Add("  try {")

    foreach ($step in $Steps) {
        $scriptLines.Add("  $step")
    }

    $scriptLines.Add("    console.log('Automation finished.');")
    $scriptLines.Add("  } catch (error) {")
    $scriptLines.Add("    console.error('Automation failed:', error);")
    $scriptLines.Add("    process.exitCode = 1;")
    $scriptLines.Add("  } finally {")

    if ($keepOpen) {
        $scriptLines.Add("    console.log('Press Enter to close the browser.');")
        $scriptLines.Add("    process.stdin.resume();")
        $scriptLines.Add("    await new Promise(resolve => process.stdin.once('data', resolve));")
        $scriptLines.Add("    process.stdin.pause();")
    }

    $scriptLines.Add("    await browser.close();")
    $scriptLines.Add("  }")
    $scriptLines.Add("})();")

    Set-Content -LiteralPath $targetPath -Value $scriptLines -Encoding UTF8
    $startPath = Write-StartBat -ScriptPath $targetPath
    Write-Ok "Saved script: $targetPath"
    Write-Ok "Saved launcher: $startPath"
    Write-Info "Run it with: `"$startPath`""
    return $true
}

$steps = New-Object System.Collections.Generic.List[string]
$exitRequested = $false

while (-not $exitRequested) {
    Show-Menu
    $choice = Read-Host "Choose an action"

    switch ($choice) {
        "1" {
            $url = Read-Required "Enter URL"
            Add-Step -Steps $steps -Code ("await page.goto({0});" -f (ConvertTo-JsString $url)) -Label "Open URL"
        }
        "2" {
            $xpath = Read-Required "Enter XPath"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).click();" -f (ConvertTo-JsString $xpath)) -Label "Click by XPath"
        }
        "3" {
            $xpath = Read-Required "Enter XPath"
            $text = Read-Required "Enter text"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).fill({1});" -f (ConvertTo-JsString $xpath), (ConvertTo-JsString $text)) -Label "Fill by XPath"
        }
        "4" {
            $xpath = Read-Required "Enter XPath"
            $text = Read-Required "Enter text"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).click();" -f (ConvertTo-JsString $xpath)) -Label "Click by XPath"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).fill({1});" -f (ConvertTo-JsString $xpath), (ConvertTo-JsString $text)) -Label "Fill clicked XPath"
        }
        "5" {
            $xpath = Read-Required "Enter XPath"
            $timeout = Read-Timeout "Timeout milliseconds (default 10000)"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).waitFor({{ state: 'visible', timeout: {1} }});" -f (ConvertTo-JsString $xpath), $timeout) -Label "Wait for XPath"
        }
        "6" {
            $milliseconds = Read-Timeout "Milliseconds to wait"
            Add-Step -Steps $steps -Code ("await page.waitForTimeout({0});" -f $milliseconds) -Label "Wait milliseconds"
        }
        "7" {
            $xpath = Read-Required "Enter XPath"
            $key = Read-Required "Enter key name"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).press({1});" -f (ConvertTo-JsString $xpath), (ConvertTo-JsString $key)) -Label "Press key by XPath"
        }
        "8" {
            $xpath = Read-Required "Enter XPath"
            $value = Read-Required "Enter option value"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).selectOption({1});" -f (ConvertTo-JsString $xpath), (ConvertTo-JsString $value)) -Label "Select option by XPath"
        }
        "9" {
            $xpath = Read-Required "Enter XPath"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).check();" -f (ConvertTo-JsString $xpath)) -Label "Check checkbox by XPath"
        }
        "10" {
            $xpath = Read-Required "Enter XPath"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).uncheck();" -f (ConvertTo-JsString $xpath)) -Label "Uncheck checkbox by XPath"
        }
        "11" {
            $xpath = Read-Required "Enter XPath"
            Add-Step -Steps $steps -Code ("await page.locator('xpath=' + {0}).hover();" -f (ConvertTo-JsString $xpath)) -Label "Hover by XPath"
        }
        "12" {
            $path = Read-Optional -Prompt "Screenshot file path (default screenshot.png)" -DefaultValue "screenshot.png"
            Add-Step -Steps $steps -Code ("await page.screenshot({{ path: {0}, fullPage: true }});" -f (ConvertTo-JsString $path)) -Label "Screenshot"
        }
        "13" {
            $code = Read-Required "Enter JavaScript code to run in the page"
            Add-Step -Steps $steps -Code ("await page.evaluate(() => {{ {0} }});" -f $code) -Label "Custom JavaScript"
        }
        "14" {
            Show-Steps -Steps $steps
        }
        "15" {
            $answer = Read-Optional -Prompt "Clear all steps? (Y/N, default N)" -DefaultValue "N"
            if ($answer -match '^(Y|y|Yes|yes)$') {
                $steps.Clear()
                Write-Ok "Steps cleared."
            }
        }
        "16" {
            if (Save-AutomationScript -Steps $steps -TargetDir $OutputDir) {
                $exitRequested = $true
            }
        }
        "0" {
            Write-WarnMsg "Exited without saving."
            $exitRequested = $true
        }
        default {
            Write-WarnMsg "Unknown action."
        }
    }
}
